### ISSUE TITLE
Client Hangs when last hash is cracked.

### ISSUE THREAD

**Issue by winxp5421** [s3inlc/hashtopolis#230]
Client(agent) version: 0.43.13

Scenario: Single hash in the hashlist. Hash gets cracked. Client hangs after uploading to the server. 

The client should request new task.

```
Progress: 83.22% | Speed:3.44GH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1
Progress: 83.45% | Speed:3.47GH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1
Progress: 83.69% | Speed:3.48GH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1
Progress: 83.92% | Speed:3.48GH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1
Progress: 84.16% | Speed:3.46GH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1
Progress: 84.62% | Speed:3.46GH/s | Cracks:1    | Accepted:1    | Zapped:0    | Queue:1
Finished processing chunk
Getting chunk...
hashfile is empty or corrupt.
```

**Comment by s3inlc** [comment]
This issue appeared also during the development of the new version, it was caused by the agents not getting unassigned from the task which was finished because all hashes got cracked and it produced a loop or errors.
Can you please test this with the current dev branch and report back if the issue is resolved there?

**Comment by winxp5421** [comment]
I will be closing this issue if you feel this issue was closed in error please re-open and explain why.
