### ISSUE TITLE
Is there a limit to the size of hashlist?

### ISSUE THREAD

**Issue by wfsunwj** [s3inlc/hashtopolis#310]
Before you submit an issue please include the following information if you do not your issue will be closed.
Your current Server version located at the bottom of any hashtopussy webpage.
0.4.3
Current Client version
0.46.2
Your current Hashcat version
3.6.0
The exact task command you are trying to run.
not important
Debug output from the client by running "hashtopussy.exe debug"
Getting task
{"action":"task","token":"dP1xysMBQE"}
{"action":"task","response":"SUCCESS","task":19,"attackcmd":"-a0 #HL# weakpasswd_11.txt","cmdpars":"--gpu-temp-disable --hash-type=0","hashlist":17,"bench":30,"statustimer":5,"files":["weakpasswd_11.txt"],"benchType":"run","hashlistAlias":"#HL#"}
Server has assigned client with Task:19 and Hashlist:17
Downloading hashlist for this task, please wait...
{"action":"hashes","token":"dP1xysMBQE","hashlist":17}
Getting chunk...
{"action":"chunk","token":"dP1xysMBQE","taskId":19}
{"action":"chunk","response":"SUCCESS","status":"fully_dispatched"}

Describe your problem in as much detail as possible " It's broke " is not a description.
There are 200,000 hash in hashlists.
![image](https://user-images.githubusercontent.com/25835567/34902138-424673ae-f850-11e7-905a-e93b22d194c5.png)

**Comment by winxp5421** [comment]
Is there a software limit on the number of hashes? No. Is there a hardware limitation very much so. Htp can handle as many hashes as the mysql server can handle. That is the limiting factor.

Htp was designed as a job cluster manager not a hash manager. Unfortunately, in order to use large hashlists you must have a beefy machine to handle that demand.

Have a look at your system resources server side while downloading a hashlist or uploading a good set of founds. If your resources are not being utilized to their full potential have a look at optimising your MySQL server settings.

**Comment by winxp5421** [comment]
I will be closing this issue if you feel this issue was closed in error please re-open and explain why.
