### ISSUE TITLE
New feature request: SQL DEBUG logging

### ISSUE THREAD

**Issue by evilmog** [s3inlc/hashtopolis#356]
If possible I'd like to request a "developer mode" where all actions that modify the database would log the executed sql statements to a file when a debug flag is set. This output would exclude select statements and only include insert, update and delete statements.

The reasoning behind this is I am working on an integration component within the company I work for including automatic importation into hashtopolis of new tasklists and often directly interface with the database, it would be handy to set a flag and log things to a file or to the screen in order to make sure I am understanding all dependencies.

Right now I have a python automagic code generator for the sqlalchemy class but some debugging info would be handy.

**Comment by s3inlc** [comment]
Ok, I see what you want to do. I guess it would be even better for you to have an API to execute actions (e.g. create tasks, add hashlists, etc.)?

Because such an API is planned, I just started with a permission rework as I wanted to have this added first and the API would be the next large feature to add.

**Comment by evilmog** [comment]
An API would be handy, but in the interim we've got a few direct SQL queries as I have a few things I'd like to integrate sooner rather than later and have no problem rewriting the code for that.

At a minimum if you could document the format for new task insertions, taskfile insertions and hashlist insertions that would be ideal.  I had hashlist insertions going but had some issues figuring out the foreign keys for tasks with files and then deletion of hashlists when done.

In fact if you could document whats needed for the SQL statements for general task maintenance that would be handy.

**Comment by s3inlc** [comment]
Ok, there is a pretty easy way to do this by adding some lines in `src/dba/AbstractModelFactory.class.php`:

`file_put_contents(dirname(__FILE__)."/db.log", $query."\n", FILE_APPEND);`

Locations to add (to cover inserts, deletions, updates). All lines based on orignal file without modification:
- Line 114
- Line 217
- Line 267
- Line 604
- Line 627
- Line 662
- Line 699

As long as it is enough for you to have the prepared statements, otherwise you just also can let you give the `$vals` array containing the values.

**Comment by s3inlc** [comment]
As the User API is now available I think I can close this issue. Please reopen if you still need some discussions or there is something missing.
