### ISSUE TITLE
Hashcat XOpenDisplay error causing Hashtopolis to set Agent as inactive

### ISSUE THREAD

**Issue by mccurls** [s3inlc/hashtopolis#370]
Your current Server version located at the bottom of any Hashtopolis webpage.

**0.5.1**

Current Client version

**0.1.3**

Your current Hashcat version
**v4.0.1**

The exact task command you are trying to run.

**Any hashcat command used by the hashtopolis agent when attempting to kick off a cracking task /job as a part of normal operation.**

Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

```
Start chunk...
CALL: ./hashcat64.bin --machine-readable --quiet --status --remove --restore-disable --potfile-disable --session=hashtopolis --status-timer 5 --outfile-check-timer=5 --outfile-check-dir=../hashlist_1 -o ../../hashlists/1.out --remove-timer=5 -s 0 -l 2228043164 ../../hashlists/1 ../../files/dictionary -p : --hash-type=0
started cracking
HC error: b'\x1b[31mXOpenDisplay() failed.\x1b[0m\n'
{'action': 'clientError', 'message': "b'\\x1b[31mXOpenDisplay() failed.\\x1b[0m\\n'", 'taskId': 10, 'token': 'LRNU8PiVFL'}
b'{"action":"clientError","response":"SUCCESS"}'
HC error: b'\n'
{'action': 'clientError', 'message': "b'\\n'", 'taskId': 10, 'token': 'LRNU8PiVFL'}
b'{"action":"clientError","response":"SUCCESS"}'
Sending keepalive progress to avoid timeout...
{'state': 2, 'chunkId': 10, 'speed': 0, 'relativeProgress': 0, 'cracks': [], 'action': 'sendProgress', 'token': 'LRNU8PiVFL', 'keyspaceProgress': 0}
b'{"action":"sendProgress","response":"ERROR","message":"Agent is marked inactive!"}'
Sending 0 cracks...
```

Apparently the hashcat error is identified by hashtopolis as something that should stop the agent from continuing. 

As a bypass to this, in the short-term and not recommended, I commented out the `err_thread` code within ./htpclient/hashcat_cracker.py (lines 60 and 63).

**Comment by winxp5421** [comment]
Ah... well here is a thought. I just seen you use hashcat 4.0.1

Hashcat 4.0.1 still tries to do fan control. Which requires an X environment to function properly. 

Please upgrade to hashcat 4.1.0 and see if this issue is still happening as Version 4.1.0 no longer supports fan control directly with hashcat.

**Comment by mccurls** [comment]
Ah I see. Hadn't realised that.

I'll give that a go.

**Comment by mccurls** [comment]
That's done it! cheers for the assist there. bit of a bugger I hadn't picked that up earlier.

However I would perhaps consider placing an client pre-requisite around hashcat being at v4.1.0 to potentially get around this problem for others?

**Comment by winxp5421** [comment]
After looking at this harder with s3 i completely missed that the client does not exit until after it sends the first status update to the server.  The server then tells the client to go "inactive" due to errors reported by the client. This entire situation could be avoided by simply checking the Ignore errors option in the client details page located at agents.php. 

My apologies mccurls, This could have been a really really quick issue to resolve if my head was out of my ass the other day.

Thanks for working with me and supplying as much detail as you could tough out this process.

**Comment by mccurls** [comment]
No worries at all! Thanks for all your help. and if I updated the client to the latest version, I probably wouldn't have even needed to ask this question at all! haha

Cheers mate.
