### ISSUE TITLE
The latest Hashcat(4.2.1) does not work on Windows 10

### ISSUE THREAD

**Issue by tai212** [s3inlc/hashtopolis#423]
$hashcat64 -m 2500 -b
hashcat (v4.2.1) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

./hashcat.hctune: No such file or directory

Started: Thu Aug 09 10:45:05 2018
Stopped: Thu Aug 09 10:45:05 2018
but  i have checked and
./hashcat.hctune file EXIST!

**Comment by s3inlc** [comment]
First of all, I think this is the wrong place for such an error, as it seems you are not running hashcat with Hashtopolis?
And since Hashcat 4.1.0, it is required to call it explicitly within the hashcat folder itself on windows. So you cannot call `hashcat-4.2.1/hashcat64.exe` from outside the directory. That's why hashcat does not find some files.
