### ISSUE TITLE
Hashrate overflow while running server on ARM (Raspberry)

### ISSUE THREAD

**Issue by TurtleForGaming** [s3inlc/hashtopolis#541]
- **Hashtopolis version:** 0.10.1+repository
- **Hashtopolis clien version:** Latest python repo
- **Hashcat version:**  Hashcat 5.1.0
- **Command:** `-1 ?u?l?d -a3 -m1000 -w4 --force #HL#  ?1?1?1?1?1?1?1?1`

**Describe your problem in as much detail as possible " It's broke " is not a description.**
I'was searching for a low power way to run hastopolis 24/7 so I installed it on my raspberry the only problem is that the hashrate of a friend (1746.01 MH/s) show's nicely but my hashrate (2.97GH/s hashcat report) displays -1100924273.00 H/s see the included pic [https://i.imgur.com/cZgLShv.png](https://i.imgur.com/cZgLShv.png) Will that affec any performance and what could be the cause are answers that I wanna know

**Comment by s3inlc** [comment]
Having a wrong hash rate should not affect anything. But it might happen that you run into issues when you have larger keyspaces (>2.1billion). 
These problems exist because you run a 32bit system. If possible, it's definitely recommended to install a 64bit OS and the 64bit php installation. If the hardware cannot do this, you just need to be careful with the tasks and you might get errors when the keyspace of a task gets too large.

**Comment by TurtleForGaming** [comment]
Ok thanks

**Comment by winxp5421** [comment]
Closing this as its not really an "issue" and it was explained well enough If you continue to have issues feel free to post up on hashtopolis.org
