### ISSUE TITLE
Estimated time incorrect?

### ISSUE THREAD

**Issue by MrMacG** [s3inlc/hashtopolis#566]
- Your current Server version located at the bottom of any Hashtopolis webpage.
**Hashtopolis: 0.11.0+repository**

- Current Client version
**0.5.0**

- Your current Hashcat version
**v5.1.0**

- The exact task command you are trying to run.
**-a3 #HL# -1 ?l?d ?1?1?1?1?1?1?1?1**

**Describe your problem in as much detail as possible " It's broke " is not a description.**

Hi!

I recently setup a Hashtopolis-server (great stuff), and have connected 3 agents so far in order to crack a list of PMKID hashes.

When I try to crack manually in hashcat with **-a3  <hashfile> -1 ?l?d ?1?1?1?1?1?1?1?1** (a-z 0-9) with a cracking rate of ~115kH/sec, the estimated time is approx. 1 year.

Now, with 3 agent in Hashtopolis, I get approx. 500kH/sec, Hashtopolis says the estimated time is (nearly 8 years).
Must be a bug, or is it something with the Attack command? 

Kind regards
MrMacG

**Comment by s3inlc** [comment]
How long did you let the task running until you looked at the estimation?

The estimation is not very accurate (especially when you didn't run the task for a long time), as it only considers the completed chunks and how much time has passed since the task started and uses this information to interpolate an estimated end time. Especially for such a long task which you have it might need some time until the estimation gets closer to the real value.

So, the estimation is to be considered with this information in mind. As long as the H/s looks accurate, you can see that it runs correctly. In your case the 500kH would make sense with the three agents if one runs with 115kH. So you could assume to have a estimated time of around 4 months.

**Comment by MrMacG** [comment]
Cool, then I Understand, thanks!
