### ISSUE TITLE
New python agent not distributed to clients

### ISSUE THREAD

**Issue by s6410** [s3inlc/hashtopolis#606]
Server: 0.12.0
Agent: 0.5.0 current-dev
Ubuntu server

I have run the current dev version of server and agent to test out new functionalty. With the new release I updated the server to 0.12.0 and tried updating the agents.

I ran the build-script in the agent folder and placed the new hashtopolis.zip in the bin-directory of the server. I updated in the GUI to reflect the change from 0.5.1 to 0.6.0. The reason for 0.5.1 is so that the current dev version of the agent was distributed to all agents.

The problem now is that when I start the agents they check in with version 0.5.1 of the agent, the debug output shows that there is a new version on the server and presents the download link but the new agent is never downloaded.

Does anyone have any ideas on what is wrong?

**Comment by s3inlc** [comment]
This must be due to a specific mistake at a certain point of the agent development. A change which was only meant for testing purposes slipped into the code, causing the client always to say that it is up-to-date. This change was removed here: https://github.com/s3inlc/hashtopolis-agent-python/commit/68fcedc25b8063c5f649f73692ba8c7c8cc14bcd

I assume that your agent dev version you had, was having this specific bug, and that's why it's never updating, even if the server tells so. The only way to fix this, is to remove the agent zip on the agent and retrieve the updated one manually e.g. with wget.

**Comment by s6410** [comment]
Thanks for the info. I'll do it manually then
