### ISSUE TITLE
Rule splitting - comments and new lines break the process

### ISSUE THREAD

**Issue by s6410** [s3inlc/hashtopolis#697]
Hashcat: 6.1.1
Hashtopolis: 0.12.0

Hashtype: 13713
Additional options for agents: -O 
#HL wordlist.txt -r rule1.txt

When I run this task it gets split into subtasks. I may have acrtivated the "split even if only one rule is used if benchmarks are too high" but this happens in a lot of other cases as well when the tasks do rule splitting.

the error message:

`[2021-03-16 07:13:41,638] [ERROR] Error during keyspace measure: Command 'hashcat.exe --keyspace --quiet ..\..\files\wordlist.txt -r ..\..\files\best64.rule_p2227-0  --hash-type=13713 -O' returned non-zero exit status 4294967295.`

This is what is present in the split rule file best64.rule_p2227-0

`## nothing, reverse, case... base stuff`

When I delete this subtasks it moves on to the next one, which works fine as long as it is an **actual rule and not a comment line or blank line.**

Has anyone else experienced this behaviour? I have checked three different tasks now to understand why it is erroring out and I can't find any other explanation.

The "non zero exit status" is likely Hashcat returning the string "No valid rules left" for lines that are not actual rules. IF this could somehow be handled by Hashtopolis or the agents, maybe it could just skip those subtasks when processing or never create them at all?

When you run --keyspace --quiet on the whole rule file Hashcat does not care about the comment lines, the problem is only manifesting when rule-splitting creates a partial-rule-file with no actual rules.

**Comment by s3inlc** [comment]
Indeed, the rule splitting feature is not that clever to split the rule files based on the actual lines. It just splits them by number of lines and if there are only few rules per split this behaviour can happen.
Regarding the original idea of the rule splitting which was introduced because of some hashcat disadvantages when using rules with small wordlists on slow hashes (or large salted hashlists), it technically is obsolete now, as hashcat introduced the -S flag which would exactly avoid this, as it makes the keyspace dependent of all combinations and not the wordlist only which then will allow better distribution again.
In the end, I don't think this behaviour of the rule splitting will be fixed, rather it probably should be removed completely as a feature as it causes more problems as it will improve at all.

**Comment by s6410** [comment]
Thank you for reply! Is there any way to turn off rule splitting completely in Hashtopolis?

**Comment by s3inlc** [comment]
Yes, when you disable it in the server config (Config -> Server -> Cracking/Tasks). The checkbox at `Disable automatic task splitting with large rule files.` must be unchecked. 
If it still happens with it disabled, then there must be a bug (which most likely will not be fixed until I will remove it completely).

**Comment by s6410** [comment]
I understand, thanks!
